//
// Created by Casey Idzikowski on 5/16/25.
//

#include "SoundSource.h"
#include "SoundDefinitions.h"
#include "SoundHelpers.cpp"

/**
 * A class for generating white noise samples for sound mixing.
 *
 * Example of a sample generated by a single line of code through random
 * floats.
 */
class WhiteNoiseSoundSource : public SoundSource {
public:
    using SoundSource::SoundSource;

    void addSoundToBuffer(float *audioData, int numSamples) override {
        for (int i = 0; i < numSamples; i++) {
            audioData[i] += makeWhiteNoise() * volume;
        }
    }

    SoundDefinitions::SoundSourceType getSoundSourceType() override {
        return WhiteNoiseSourceType;
    }

private:
    /**
     * Helper function to generate a white noise sample.
     * @return A random float between -0.6 and 0.6
     */
    static float makeWhiteNoise() {
        return CommonSounds::whiteNoise();
    }

    static constexpr SoundDefinitions::SoundSourceType WhiteNoiseSourceType = SoundDefinitions::SoundSourceType::WHITE_NOISE;
};
